import React, {useState, useEffect, useRef} from 'react'
import { useRouter } from 'next/router'
import Body from '../../components/Body'
import Content from '../../components/Content'
import ModalDialog from '../../components/Modal'
import Link from 'next/link'
import Image from 'next/image'
import Collapse from '@mui/material/Collapse';
import IconButton from '@mui/material/IconButton';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell, {tableCellClasses} from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableRow from '@mui/material/TableRow';
import Paper from '@mui/material/Paper';
// import KeyboardArrowDownIcon from '@mui/icons-material/KeyboardArrowDown';
// import KeyboardArrowUpIcon from '@mui/icons-material/KeyboardArrowUp';

import moment from 'moment';

import { styled } from '@mui/material/styles';
import t from '../../public/translation/locale'
import ApiService from '../../services/ApiService';
import Papa from 'papaparse';

const KeyboardArrowDownIcon = () => {
  return <Image src='/images/ic_arrow_expand_large.svg' width={30} height={30} alt='info'></Image>
}

const KeyboardArrowUpIcon = () => {
  return <Image src='/images/ic_arrow_collapse_large.svg' width={30} height={30} alt='info'></Image>
}

const StyledTableCell = styled(TableCell)(({ theme }) => ({
    [`&.${tableCellClasses.head}`]: {
      backgroundColor: theme.palette.common.black,
      color: theme.palette.common.white
    },
    [`&.${tableCellClasses.body}`]: {
      fontSize: 14,
    },
  }));

  function formatDate(date) {
    const d = new Date(date)
    const userLocale = navigator.language.substring(0,2);
    const options = {
      year: 'numeric',
      month: userLocale == 'en' ? 'short' : 'long' ,
      day: 'numeric',
    };
    const formattedDate = d.toLocaleDateString(userLocale, options);
    return formattedDate
  
  }

  function formatTime(date) {
    const momentDate = moment.utc(date);
    const localDate = momentDate.local();

    const formattedDate = localDate.format('YYYY-MM-DD HH:mm:ss');
    return formattedDate.split(' ')
  
  }

function Row(props) {
    const { row } = props;
    const [open, setOpen] = React.useState(false);
  
    return (
      <React.Fragment>
        <TableRow className='row-pointer' onClick={() => setOpen(!open)}>
          <TableCell className='fields-generated'>
            <div className="d-flex">
                <div>

                    <p className="font-16 history-datetime d-flex"><p>{formatDate(row.timeStamp)}</p> <p className='history-editor mlr-10'>|</p><p>{formatTime(row.timeStamp)[1]} {formatTime(row.timeStamp)[2]}</p></p>
                    {row.objectType == "Generate" 
                    
                    ?
                    
                    <p className='font-13 history-editor'>{row.actionDisplay} | {row.creditUsed} credits used</p>
                     :
                     
                    <p className='font-13 history-editor'>{row.actionDisplay}</p>
                     }

                    {/* <p className='font-13 history-editor'>{row.objectType == "Generate" ? 'Generated by' : row.objectType == "Update" ? 'Saved by' : `Transferred to ${row.objectType.split(",").pop()} by`} {row.editors.toString()}</p> */}
                </div>
                <div className="ml-auto">
                    <button aria-label="expand row" style={{background: 'inherit', border: 'none'}} onClick={() => setOpen(!open)}>
                        {open ? <KeyboardArrowUpIcon /> : <KeyboardArrowDownIcon />}
                    </button>
                </div>
            </div>
          </TableCell>
        </TableRow>
        <TableRow>
          <TableCell style={{ padding: 0, borderBottom: 0}} colSpan={12}>
            <Collapse in={open} timeout="auto" unmountOnExit>
                 <Table sx={{ minWidth: 700, border:'none' }} >
                  <TableBody>
                      <StyledTableCell sx={{borderBottom: 'none'}} >
                        
                          {row.fields.map((r,i) => (
                              <div key={i}>
                                <div>
                                  <p className='font-14 field history'>{r.fieldType}</p>
                                </div>
                                  {
                                    r.value.map((v,ix) => (
                                   <>
                                           <div key={ix} >
                                          < p className='font-13 history'  >• {v}</p>
                                          </div>
                                  {ix < r.value.length - 1 && (
                                    <hr className="solid"></hr>
                                  )}</>
                                      
                                    ))
                                  }
                                  {/* <hr className="solid"></hr> */}
                              </div>
                              
                          ))}
                      </StyledTableCell>
                  </TableBody>
                </Table>
            </Collapse>
          </TableCell>
        </TableRow>
      </React.Fragment>
    );
  }


export default function HistoryLogs({userData}) {
  const router = useRouter();

  
const [data, setData] = useState(null)

const https = require("https");
const [storeId, setStoreid] = useState('');
const [page, setPage] = useState(0);
const [loading, setLoading] = useState(true);
const [hasMore, setHasMore] = useState(true);
const [continuationToken, setContinuationToken] = useState(null);
const [translation, setTranslation] = useState(null);

const [queryParanms, setQueryParams] = useState({});

const [generatingCsv, setGeneratingCsv] = useState(false);
const [selectedUrl, setSelectedUrl] = useState('');
async function getReports(){

  const emailRegex = /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/g;
  
  const urlParams = new URLSearchParams(window.location.search)
 
  const url = urlParams.get('url')
  const urlId = urlParams.get('urlId')
  const storeId = urlParams.get('storeId')
  const textId = urlParams.get('textId')
  const startDate = urlParams.get('startDate')
  const endDate = urlParams.get('endDate')
  const user = urlParams.get('user')

  //create query params object based on url params
  let queryParams = {
    url: url,
    urlId: urlId,
    storeId: storeId,
    textId: textId,
    startDate: startDate,
    endDate: endDate,
    user: user
  }
  if (window.location.search != "")
    {
      localStorage.setItem('historyParams', JSON.stringify(queryParams))
    }
    else
    {
      const historyParams = localStorage.getItem('historyParams')
      queryParams = JSON.parse(historyParams)
    }
  setQueryParams(queryParams)

     if (queryParams.url != undefined)
        setSelectedUrl(url)
    
     setStoreid(queryParams.storeId)
  

    const formData = new FormData()

    formData.append('type', 'Product')
    if (queryParams.urlId != "" && queryParams.urlId != undefined)
      formData.append('urlId', queryParams.urlId)

    if (queryParams.storeId != "" && queryParams.storeId != undefined)
      formData.append('storeId', queryParams.storeId)

    if (queryParams.textId != "" && queryParams.textId != undefined)
      formData.append('textId', queryParams.textId)

    if (continuationToken != null)
      formData.append('continuationToken', continuationToken)

    if (queryParams.startDate != "" && queryParams.startDate != undefined)
      formData.append('startDate', queryParams.startDate)

    if (queryParams.endDate != "" && queryParams.endDate != undefined)
      formData.append('endDate', queryParams.endDate)

    if (queryParams.user != "All" && queryParams.user != undefined)
    {
      const userMatch = window.location.search.match(emailRegex);
      formData.append('userName', encodeURI(userMatch))
    }
    if ((queryParams.storeId != undefined && queryParams.urlId != undefined) || queryParams.textId != undefined)
    {
      
    await ApiService.postWithFormData(`/Reporting/History`, formData)
    .then(res => {
           if (res.data.histories.length > 0){
        
        setContinuationToken(res.data.continuationToken)
        if (res.data.continuationToken == null)
        {
          setHasMore(false)
        }
        else
        {
          setHasMore(true)
        }
        if (data != null)
        {
          setData([...data, ...res.data.histories])
        }else{
          setData(res.data.histories)
        }
      }
      else
      {
        setHasMore(false)
      }
    })
    .catch(error => {
           setLoading(false);
          setHasMore(false)
    });
    }

   
}

const exportToCsv = async (json) => {
  try {
    // Parse JSON from request body
    const jsonArray = json;

    // Check if the input is valid
    if (!Array.isArray(jsonArray)) {
      return res.status(400).json({ error: 'Invalid JSON format. Expected an array of objects.' });
    }

    // Flatten each object in the array
    const rows = jsonArray.flatMap(data => {
      return data.fields.flatMap(field => {
        let type = '';
        let recordId = '';
        try {
          const splits = (data.objectId || '').split('_');
          type = splits[1] || '';
          recordId = splits[2] || '';
        } catch (error) {
          type = '';
          recordId = '';
        }

        return field.value.map(value => ({
          'Store': selectedUrl,
          'Store ID': data.storeId,
          'Type': type,
          'Record ID': recordId,
          'Request ID': data.requestId,
          'Text ID': field.documentId,
          'Editor': data.editor,
          'Action': data.actionDisplay.split("by")[0].trim(),
          'Text Type': field.fieldType,
          'Text': value,
          'Date and Time': data.timeStamp + 'Z' // Format timestamp,
        }));
      });
    });
    const startDateObj = new Date(Number(queryParanms.startDate)).toLocaleDateString()
    const endDateObj = new Date(Number(queryParanms.endDate)).toLocaleDateString()


    const today = new Date().getTime()
    const fileName = `HistoryLogs_${startDateObj}-${endDateObj}_${today}.csv`;
    


// Convert rows with custom headers using Papa.unparse
    const csv = Papa.unparse({
      fields: ['Store','Store ID', 'Type', 'Record ID', 'Request ID', 'Text ID', 'Editor', 'Action', 'Text Type', 'Text', 'Date and Time'],
      data: rows
    });

    const blob = new Blob([csv], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', fileName);
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.URL.revokeObjectURL(url);
    
    setGeneratingCsv(false);
  } catch (error) {
  }
}
const exportHistory = async () => {
  
  let exportContinuationToken = ''
  let exportHasMore = true
  let exportData = []

  const postAndCheckHasMore = async () => {
    
  const formData = new FormData()
  formData.append('type', 'Product')
  if (queryParanms.urlId != "" && queryParanms.urlId != undefined)
    formData.append('urlId', queryParanms.urlId)
  if (queryParanms.storeId != "" && storeId != undefined)
    formData.append('storeId', storeId)
  if (queryParanms.textId != "" && queryParanms.textId != undefined)
    formData.append('textId', queryParanms.textId)
  if (continuationToken != null)
    formData.append('continuationToken', exportContinuationToken)
  if (queryParanms.startDate != "" && queryParanms.startDate != undefined)
    formData.append('startDate', queryParanms.startDate)
  if (queryParanms.endDate != "" && queryParanms.endDate != undefined)
    formData.append('endDate', queryParanms.endDate)
  
    if ((queryParanms.storeId != undefined && queryParanms.urlId != undefined) || queryParanms.textId != undefined) {
      setGeneratingCsv(true);
      await ApiService.postWithFormData(`/Reporting/History`, formData)
        .then(res => {
          if (res.data.histories.length > 0) {
            exportContinuationToken = res.data.continuationToken
            if (res.data.continuationToken == null) {
              
              exportHasMore = false
              
              exportData = [...exportData, ...res.data.histories]
              exportToCsv(exportData)
            }
            else
            {
              if (exportData.length > 0) {
                exportData = [...exportData, ...res.data.histories] 
              } else {
                exportData = [...res.data.histories]
              }
  
              if (exportHasMore) {
                // Update continuationToken and repeat the post
                exportContinuationToken = res.data.continuationToken
                postAndCheckHasMore()
              }
            }

          } else {
            exportHasMore = false
          }
        })
        .catch(error => {
          exportHasMore = false
        })
    }
  }

  postAndCheckHasMore()
 
}
  useEffect(() => {
    async function Init(){
      
      const locale = navigator.language.substring(0,2);
      setTranslation(t[locale] != undefined ? t[locale].Content["HistoryLogs"] : t["en"].Content["HistoryLogs"])
    }

    async function getUser() {
      const AuthenticationService = require('../../services/AuthenticationService').default
      await AuthenticationService.getUser().then(u => {
         getReports()
        Init() 
      })
    }
    getUser()
  },[])
  useEffect(() => {
    if (data)
    {
      const element = document.getElementById('main-container');
      function handleScroll() {
        const scrollableHeight = element.scrollHeight - element.clientHeight;
        if (element.scrollTop === scrollableHeight) {
          setPage(page + 1);
          if (hasMore)
          {
            getReports()
          }
        }
      }
      if (element)
      {
        element.addEventListener('scroll', handleScroll);
        return () => element.removeEventListener("scroll", handleScroll);
      }
    }
  },[data])
  const isDomain = (str) => {
    if (!/^https?:\/\//.test(str)) 
    {
        return false;
    }
    const match = str.match(/^https?:\/\/([^\/:]+)(:\d+)?(\/.*)?$/);
    if (!match) return false;

    const hostname = match[1];

    if (hostname.length < 2) {
        return false;
    }
    
    if (/^\d{1,3}(\.\d{1,3}){3}$/.test(hostname)) {
        return false;
    }
    const url = new URL(str);
    const isUrl = /^[a-zA-Z0-9-]+\.[a-zA-Z0-9.-]+$/.test(url.hostname);
    if (!isUrl)
    {
      const regex = /^(https?:\/\/)?([a-zA-Z0-9-]+\.)+[a-zA-Z0-9-]{2,}$/;
      const isTrue = regex.test(str);
      return isTrue;
    }
    return isUrl;
 }
  if (translation && userData)
  return (
    <>
    <ModalDialog target="billing" type="billing" click={() => {router.push('/billing')}}/>
      <Body>
        <Content backgroundclass={"scrollable-container"}>
     <div className="header d-flex mb-30 download-header">
        {/* <div className='font-14'><Link href="/reports"><Image className='mr-8' src="/images/ic-back.svg" width="8" height="10" alt='back'></Image>Back to reporting</Link></div> */}
        <p className={`d-flex mb-15`}><p className={`back-btn`} onClick={() => router.push('/reports')}></p>History logs</p>

        {/* <button className="back-btn" onClick={()=>{router.push('/reports')}}>
        </button> */}
        <div className="right ms-auto">
        {data != null &&
          <button id='exportCsv' type="button" className={`btn btn-primary submit-button ${generatingCsv ? 'disabled' : ''}`} onClick={exportHistory} disabled={generatingCsv} >
            {generatingCsv ? (
              <>
                <span className="spinner-border" role="status" aria-hidden="true"></span>
                <span className="visually-hidden">Loading...</span>
              </>
            ) : (
              "Export as CSV"
            )}
          </button>
        }
      </div>
    </div>
    <div className='mb-36 d-flex '>
           {isDomain(`https://` + storeId) ? <Link passHref={true} href={`https://`+ storeId} className='font-16 mb-14 sub-p link'>{storeId}</Link> : <p className='font-16 mb-14 sub-p'>{storeId}</p>}
          
      
    </div>
    <div className='history-note mb-14 mt-36 font-16'>
      
            <p><Image className='info-icon' src='/images/info-icon.svg' width={16} height={16} alt='info'></Image>{translation["Information"]}</p>
    </div>
    <TableContainer className='no-shadow' component={Paper}>
      <Table sx={{ minWidth: 700 }} aria-label="customized table">
        <TableBody>
        { data != null && data.map((row, index) => (
          <div key={index}  className='fields-container'>
            <Row key={`row-${index}`} row={row} />
          </div>
          ))}
        </TableBody>
      </Table>
      {hasMore && (
        <div id="loader" className='text-center'>Loading...</div>
      )}
      {!hasMore && <p className='text-center'>History ends here</p>}
    </TableContainer>
    {/* {loading && <p>Loading...</p>} */}
      
    </Content>  
      </Body>
    </>
  )
}
